# Generated by Django 3.1.4 on 2021-04-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210331_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(blank=True, default='01234567890', null=True),
        ),
    ]
